name: Update Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update-contribs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6.0.0
      with:
        python-version: "3.12"
        cache: pip
    - run: pip install -r requirements.txt
    - run: python contribs.py your-handle.png --dir repo --num-commits "${{ vars.NUM_COMMITS }}"  --name "${{ vars.AUTHOR_NAME }}" --email "${{ vars.AUTHOR_EMAIL }}"
    - run: gh repo delete your-handle/contributions --yes || true
    - run: gh repo create your-handle/contributions --private --source repo --push
